# Generated by Django 4.2.9 on 2024-01-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_identiant', models.CharField(max_length=90)),
                ('command_client_name', models.CharField(max_length=150)),
                ('command_client_phone_number', models.CharField(max_length=12)),
                ('place_of_delivery', models.CharField(max_length=50)),
                ('command_status', models.CharField(choices=[('in progress', 'in progress'), ('finished', 'finished'), ('not actif', 'not actif')], max_length=50)),
            ],
        ),
    ]
