# Generated by Django 4.2.9 on 2024-01-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_food_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='creator',
            field=models.CharField(default='amer', max_length=50),
        ),
    ]
