# Generated by Django 4.2.9 on 2024-01-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuappmodel',
            name='menu_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
