# Generated by Django 4.2.9 on 2024-01-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0002_menuappmodel_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuappmodel',
            name='menu_updater',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
