# Generated by Django 4.2.9 on 2024-01-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0003_menuappmodel_menu_updater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('menu_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MenuApp.menuappmodel')),
            ],
        ),
    ]
