# Generated by Django 4.2.9 on 2024-01-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuApp', '0005_eater_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='eater',
            name='updater',
            field=models.CharField(default='_______', max_length=255),
        ),
    ]
